feat(base_branch_check): Ensure PR contains base branch

diff --git a/.github/workflows/pull-requests.yaml b/.github/workflows/pull-requests.yaml
--- a/.github/workflows/pull-requests.yaml
+++ b/.github/workflows/pull-requests.yaml
@@ -45,3 +45,27 @@ jobs:
       #   custom-domains: my-custom-domain.io another.domain.com
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+  pr_contains_current_head:
+    runs-on: ubuntu-latest
+    name: Ensure PR does not require rebase
+    steps:
+
+
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      
+      - name: Verify PR contains latest base branch
+        shell: bash
+        run: |
+          git fetch origin "${{ github.event.pull_request.base.ref }}" --no-tags
+
+          if ! git merge-base --is-ancestor \
+            "origin/${{ github.event.pull_request.base.ref }}" \
+            "${{ github.event.pull_request.head.sha }}"; then
+            echo "::error::PR branch does not contain the latest ${{ github.event.pull_request.base.ref }} branch HEAD."
+            exit 1
+          fi
